### PR TITLE
Pick nits

### PR DESCRIPTION
**Pull request by kemitchell**
Following on from #26:

1. Ran `aspell check` on everything.

2. Fixed capitalization of "Google Hangouts", just 'cause I saw it while I was `aspell`in' about.

### CODE REVIEW

**Comment by kemitchell** [comment]
Rebased onto #28.

**Comment by ashleygwilliams** [comment]
status of this PR? it's super old, doing some clean up rn

**Comment by kemitchell** [comment]
I've force-pushed a new branch off current master that adds just the spelling and other small changes. I did _not_ bring forward the changes to hyperlinks that Isaac commented. This should be good to land.

**Comment by ashleygwilliams** [comment]
LGTM. thanks! merging.

**Pull request merged**
