### PR TITLE
Use tools to check hyperlinks

### PR DESCRIPTION
**Pull request by kemitchell**
This small PR replaces #26.

It:

1. Configures Travis CI to check policy files, rendered with marked via revised `Makefile`, for broken hyperlinks with html-proofer.

2. Fixes a few broken hyperlinks.

### CODE REVIEW

**Comment by kemitchell** [comment]
@seldo: Apropos of the `marked`-based build chain in the `Makefile`: Could I put a placeholder for "last updated" date in the Markdown and swap it out in the `Makefile` with a shell script? Would that produce correct HTML on npmjs.com?

**Comment by kemitchell** [comment]
@isaacs & @seldo: FYI, this PR contains a substantive correction that fixes a link to the new, consolidated terms for Private Packages. It's the highest priority from my point of view.

**Comment by isaacs** [comment]
Just updated the recruiting doc myself.  No biggie.

**Comment by kemitchell** [comment]
Thanks for fixing with the merge.

**Pull request merged**
