### PR TITLE
Clarify user content license

### PR DESCRIPTION
**Pull request by kemitchell**
Responsive to #30, with very special thanks to @rmg

This PR refines the terms for npm Open-Source that grant npm, Inc. the license it needs to publish user content. Its purpose is to clarify our original intent: To make explicit the permission users give npm to make their content available to other users.

As a legal drafting task, this is a bit tricky, in that npm, Inc. makes lots of copies, sends them to lots of people, and also needs rights to inspect and process the contents of code packages, say to check bundledDependencies. In the future, as npm does more on the registry and website to improve install speed and package discovery, we may need to revisit this language again.

For now, however, we've had great feedback on perceived overbreadth in the opposite direction: Folks are concerned the current language might give npm, Inc. rights to "use" software in its own products and services beyond the bounds of the software license terms on which users are otherwise making their work available. This PR addresses that miscommunication head-on, hopefully without sacrificing readability.

npm, Inc. set me a clear (and rare!) design goal to make these terms as readable as possible for all npm users. We know the vast majority of users won't have counsel on call. However, we implore especially those representing commercial concerns to run this change (and the rest of the terms) past their IP lawyers. npm, Inc. has specially instructed me to take part in Issue and PRs here, but counsel should feel free to contact npm, Inc. to get in touch with me. I'll be happy to chat lawyer-to-lawyer, in the usual way, and grateful for all considered input. We want to do right by the whole npm community, both when they're hacking on the weekend and at their 9-5s.

@seldo & @isaacs: I'd like to leave this open for a day or so at least, especially if that gives @jasnell a chance to feed back. I'll plan to mention you when I think we're ready to merge (with new "last updated" date).

Quoting a previous intro in https://github.com/npm/policies/issues/30#issuecomment-159140855

> Just for the benefit of others who aren't aware: I'm legal counsel for npm, Inc. They've instructed me to do as much as I can on the terms and policies here on GitHub, as transparently as possible. That does not include giving legal advice. (Don't rely on what I say for your own purposes. Get your own lawyer and talk your needs through with them.) But it does include responding to and incorporating good feedback from the community.

### CODE REVIEW

**Comment by jasnell** [comment]
I appreciate that but it's going to take a bit longer than a day as I'm
technically on vacation this week. Going ahead and close if you'd like and
I'll get you feedback as soon as I'm able.

**Comment by kemitchell** [comment]
@jasnell Gotcha. Sorry for bothering on vacation!

**Comment by rmg** [comment]
I like it :+1:

**Comment by kemitchell** [comment]
@rmg, just so you know, there is a little back-and-forth on this internally. Not because anybody at npm wants a free pass to use everybody's packages in npm products, but to make make sure npm can analyse packages for optimization, discovery, etc.

I'll probably amend this PR slightly later this week, but I highly doubt you'll find any unwelcome surprises.

Thanks so much for your patience and you input. Especially this late!

**Comment by jasnell** [comment]
After a quick look this looks *much* better!

**Comment by isaacs** [comment]
> but does not give npm any additional rights to build products or services using Your Content

I'm a little bit fuzzy on this bit.

In the context of this conversation, I think we all grok that this means "you don't give npm the right to `require("your-content")` in their registry codebase, or ship it as part of their npm On-Site software product."

However, since "use" is vague, if we wanted to build a service where someone can pay to run an analysis job that shows all the places where a certain line of code exists in npm packages, then that product would "use" Your Content as a sort of raw content-material.  It would be unfortunate if such a product required a change to the ToS.

I think we all agree that this hypothetical analysis product "uses" Your Content in a fundamentally different way than how `express` "uses" `connect` or the npm registry "uses" CouchDB.  It's more like how flickr "uses" your photos or rapgenius "uses" lyrics and user comments.

That difference needs to be clear here, if we intend to give up one of those rights and not the other.

**Comment by jasnell** [comment]
@isaacs ... for that kind of mechanism, I think it may be worthwhile building in a kind of opt-in mechanism for packages that use a custom or commercial license. Since npm already has the SPDX support built in, any package that uses a non-SPDX recognized license would be excluded by default from that kind of analysis service. Some piece of metadata could be added to the package.json to indicate that the publisher accepts the terms of that additional service. Packages that use an SPDX compatible open source license would not need to deal with that additional piece.

**Comment by kemitchell** [comment]
I've just pushed an additional commit that I think makes a workable distinction between:

1. "using" code in packages to improve delivery, discovery, etc. through npm, Inc.services
2. "using" the code as a functional component of npm products in ways the authors didn't choose to license

In case this gets amended, squashed, or folks would just prefer to read by e-mail, here is the revised language:

> You own Your Content, but grant npm a free-of-charge license to provide Your Content to users of npm Services. That license allows npm to make copies of and publish Your Content, as well as to analyze Your Content and share results with users of npm Services. npm may run computer code in Your Content to analyze it, but the license does not give npm any additional rights to run your code for its functionality in npm products or services. The license lasts, for each piece of Your Content, until the last copy disappears from npm's backups, caches, and other systems, after you delete it from the Website or the Public Registry.

This isn't final, though from my point of view it's shippable. To the extent folks can weigh in, we'd much appreciate it.

**Comment by isaacs** [comment]
This addresses my concerns, and is more explicit about what kind of "use" we plan.  Love it.

@jasnell @rmg does this work for you?

**Comment by rmg** [comment]
I like it. I've always made a distinction in my mind between use/execute and consume/read, so thank you @isaacs for the background on how the term "use" came in to play in the first place.

Now that I'm thinking about the topic... Does this mean npm Inc is the only one who is actually allowed to crawl and analyze the registry contents?

**Comment by kemitchell** [comment]
Amended to update "last updated" dates. @isaacs, feel free to merge. We can always revisit if @jasnell comes back with more feedback.

Thanks again to all who've taken time to help make this clearer. I hope everyone had a restful holiday break.

**Comment by kemitchell** [comment]
Amended to bump "last updated" again. Good to merge.

**Comment by kemitchell** [comment]
Appreciate it, @isaacs. Special thanks again to @rmg and @jasnell.

**Comment by jasnell** [comment]
@kemitchell my apologies for not getting back sooner, I'm still buried catching up after vacation. This changes here look good. Thank for the clarifications.

One additional change that I might suggest: Given that the old "bad" license that's still currently being distributed still points to the website, some indication on the server side terms of service ought to indicate that nothing in the ToS should be considered to apply to the general use of the npm client when using any registry endpoint other than npmjs.org. Doing so would not eliminate the need to update the client side license as soon as we can, but it would alleviate the concern that using the client would automatically imply acceptance of the site ToS.

**Comment by kemitchell** [comment]
@jasnell, that's great feedback.

**Comment by kemitchell** [comment]
@jasnell I will give your idea some thought. We're definitely of a mind to make whatever Node.js decides to do as easy and effective as possible. I'm not yet sure what more language in our terms could or would do.

Frankly, I'm also very reluctant to fan the fire raging over at nodejs/node, by symbolic gestures or otherwise. That discussion desperately needs informed, independent legal opinion, which I understand, thanks to you and Rod and others, is now inbound. Anything else is probably just fuel.

**Pull request merged**
